### ISSUE TITLE
set_ak_column: problem with a new column on the reduction step.

### ISSUE THREAD

**Issue by hephysicist** [columnflow/columnflow#394] opened 2024-02-06 10:38 UTC
I'm using set_ak_columnf32 function and want to add a variable for the existing Muon object on the selection step. Here is an example:
```events = set_ak_column_f32(events, "Muon.mT", mT_values)```
The docstring for the parent function set_ak_column says that if there is no intermediate field, they should be created automatically. I have the Muon field, so I expect for mT column to be added to the Muon object.  
Unfortunately on the reduction step, I get the error:

```
 File "/afs/cern.ch/user/s/stzakhar/work/higgs_cp/modules/columnflow/columnflow/columnar_util.py", line 709, in set_ak_column
    ak_array = ak.with_field(ak_array, value, sub_route.fields)
  File "/afs/cern.ch/user/s/stzakhar/work/higgs_cp/data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/awkward/_dispatch.py", line 68, in dispatch
    return gen_or_result
  File "/afs/cern.ch/user/s/stzakhar/work/higgs_cp/data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/awkward/_errors.py", line 67, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/afs/cern.ch/user/s/stzakhar/work/higgs_cp/data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/awkward/_errors.py", line 82, in handle_exception
    raise self.decorate_exception(cls, exception)
ValueError: cannot broadcast nested list (in compiled code: https://github.com/scikit-hep/awkward/blob/awkward-cpp-24/awkward-cpp/src/cpu-kernels/awkward_ListArray_broadcast_tooffsets.cpp#L27)

This error occurred while calling

    ak.with_field(
        <NanoEventsArray [<event 1:                32:                31197>, ...] type='...'>
        <Array [[], [], [], [], ..., [], [], []] type='53146 * var * float32'>
        ('Muon', 'mT')
```
This means that the column didn't belong to the Muon object and when the skimming had been done, the mT column was not affected. To calculate mT, I'm using kinematic variables of the muon so storing this variable attached to the Muon object is useful. 
Did you see this behaviour before?

**Comment by pkausw** [comment] 2024-02-06 10:53
Hi @hephysicist ,

thanks for the question! It's a little hard to make a definitive answer, can you point us to a full example somewhere? 

That being said, I have seen similar cases where the problem was actually that the dimensions of the arrays do not match. In these cases, there was a mismatch on the axis 0, i.e. the number of events had changed when creating the new column (in your case `Muon.mT`). Did you apply any masks when you calculated your `mT` column? Note that during the `SelectEvents` task, we do not actually discard any events yet. From the top of my head, there are two mechanism you can use to create meaningful values under consideration of any mask:
- you can use the [ak.mask](https://awkward-array.org/doc/main/reference/generated/ak.mask.html) function, which will not reduce dimensions but will fill `None` values where your mask is `False`. Afterwards, you can use the [ak.fill_none](https://awkward-array.org/doc/main/reference/generated/ak.fill_none.html) function to fill the `None` values with any default value, e.g. the `EMPTY_FLOAT` value from cf (which is also what I would recommend in your case)
-  If you already have a column with the right dimensions on axis 0, you can also use the [ak.where](https://awkward-array.org/doc/main/reference/generated/ak.where.html) to fill values according to the mask.

But I think the problem will become clearer if you can provide us with an example to reproduce the error.

Cheers,
Philip

**Comment by hephysicist** [comment] 2024-02-06 14:35
Hi @pkausw 
Let me describe the problem in detail. 
I want to produce the mT column using the producer function listed below:
```python
@producer(
    uses = 
    {
        f"Muon.{var}" for var in ["pt","phi"]
    } | {
        f"MET.{var}" for var in ["pt","phi"] 
    } | {attach_coffea_behavior},
    produces={
        "Muon.mT"
    },
)
def mT(self: Producer, events: ak.Array, **kwargs) -> ak.Array:
    
    def calc_mt(muon, met):
        cos_dphi = np.cos(muon.phi - met.phi)
        mT_vals = np.sqrt(2*muon.pt*met.pt*(1. - cos_dphi))
        return ak.fill_none(mT_vals, EMPTY_FLOAT)
    
    initial_dim = ak.num(events.Muon)
    (_, met_br) = ak.broadcast_arrays(events.Muon, events.MET[:,np.newaxis])

    flat_muon = ak.flatten(events.Muon, axis=1)
    flat_met  = ak.flatten(met_br,      axis=1)
    
    mT_values = ak.unflatten(calc_mt(flat_muon, flat_met), initial_dim,axis=0)
    
    events = set_ak_column_f32(events, Route("Muon.mT"), mT_values)
    return events
```
Then in the main selector, I simply call this function: 
```python
events = self[mT](events, **kwargs)
```
It has to be done in the selection section cos I want to use this variable to perform the selection. It's required to have mT as a field of the Muon object since I'm using muon kinematics and MET, so for control, it is useful that the reduction step will also skim mT variable. 
Several functions later I perform the selection of a single Muon for each event and produce a muon index array that will be used in the reduction step. So the output of the last function before the reduce() looks like:
```
...
 return events, SelectionResult(
        steps = {
            "extra_lep_veto" : extra_lepton_veto,
        },
        objects={
            "Muon": {
                "Muon": pair_mu_idx
            },
            "Tau": {
                "Tau": pair_tau_idx
            }
        }
    )
```
Where pair_mu_idx contains indices of the selected muons. 

I'm aware of the solution with masking and then filling Nones. This requires the production of a separate mT column that isn't connected to the Muon object. However, this is not quite safe and could potentially cause future bugs because I'll have to skim only one variable by hand independent of the Muon object set. Also there gonna be more variables to be added in the selection step. 

Best,
Stepan

**Comment by mafrahm** [comment] 2024-02-07 09:38
Hi @hephysicist, this is not really solving the issue you have potentially found, but as an alternative solution, you could also try calculating you mT feature without flattening + unflattening, e.g. like this:

```python
cos_dhi = np.cos(events.Muon.delta_phi(events.MET))
mT_values = np.sqrt(2 * events.Muon.pt * events.MET.pt * (1 - np.cos(dphi)))
events = set_ak_column_f32(events, Route("Muon.mT"), mT_values)
```

I personally prefer to work with awkward arrays as much as possible, but of course, this is up to preferences.

**Comment by hephysicist** [comment] 2024-02-07 10:55
Hi @mafrahm thanks for the suggestion! I'll try to refactor the code. 
Just for an update: I tried to remove mT column at the end of the selection and everything worked well. However, now have to create it twice: at the selection and production tasks. So it's probably connected to how the selector treats the Muon object. 

Cheers,
Stepan.

**Comment by pkausw** [comment] 2024-02-12 14:35
Hey @hephysicist ,

Thank you for providing the code that caused the issue for you. I just tried it out with the latest version of columnflow. Here is what I tried
- tried to run the producer by itself
- tried to include it into a selector
- tried it out with tt_sl and tt_dl events.

It all worked fine for me and I was not able to reproduce your error. Can you try to update columnflow to the latest version on the master branch and try again? Also, which version of cf do you currently use (i.e. which commit hash)?

Cheers,
Philip

**Comment by hephysicist** [comment] 2024-02-12 16:29
Hi Philip!
I updated columnflow and checked everything on the new version. 
Still, see the problem and here is the hash of the commit:
16d35bb2f25f62f9110a8f1089e8dc5c62b29825
I'm also trying to have some checks to point out the exact place where the error happens. 

Best, 
Stepan.

**Comment by hephysicist** [comment] 2024-02-12 16:54
https://github.com/hephysicist/higgs_cp/tree/master
Here it is.

**Comment by pkausw** [comment] 2024-02-13 17:59
Hi @hephysicist ,

thanks for pointing me to your code. I set it up, but had to change the following things:
- I don't think you have included your `cmsdb` entries in a branch, did you? In any case, I had no access to your default run3 ntuples you produced, so I had to switch to the run2 2017 nanoAODv9 samples
- Since I don't have access to your nanoAODs, I had no access to some of columns (all related to DeepTauv2p5). I excluded these selectors in the default selector
- I also commented out the `remove_ak_column` command that would have removed the new `Muon.mT` column

I ran this command

```
law run cf.SelectEvents --dataset tt_dl_powheg --branch 0 --version test --selector default --config run2_2017_nano_v9_limited
```

I didn't try a lot, and right now I don't select any events at all, but this command still runs through. Note that the definition of the producer in your repo is different from the definition you've sent us in this thread, is that on purpose? Overall, I still can't reproduce the error, but I also can't do the exact same setup of course. Maybe this already helps debugging, or maybe wen can also
- iterate again to synchronize the setups,
- talk offline to try to figure this out.

**Comment by hephysicist** [comment] 2024-02-14 13:59
Hi @pkausw ,
Thanks a lot for your efforts! For now, I have a quick fix for this problem, so let's talk offline when you have free time. 

Best, 
Stepan.

**Comment by pkausw** [comment] 2024-03-20 14:00
Hi @hephysicist , is this still an issue? If not, we'd appreciate it if you could close it :)

**Comment by pkausw** [comment] 2024-04-24 10:03
Since there aren't any updates in this issue, I'll close it

**Closed by pkausw** 2024-04-24 10:03 UTC
Labels: priority-medium, CMS
