### ISSUE TITLE
cf.CreateYieldTable is not working

### ISSUE THREAD

**Issue by aalvesan** [columnflow/columnflow#491] opened 2024-07-08 12:35 UTC
Independent to which categories are defined, the yield in the table is always shown as zero..

**Comment by mafrahm** [comment] 2024-07-10 08:39
Hi @aalvesan, I cannot reproduce the issue. Are you sure that you pass the correct `category_ids` column when creating histograms?

**Comment by pkausw** [comment] 2024-08-05 07:49
Hi @aalvesan @mafrahm , is this issue still on going? Has there been any progress?

**Comment by mafrahm** [comment] 2024-08-16 09:01
I'll close this issue since as far as I know there is no framework-related issue. Feel free to reopen this issue or open a discussion if there are still any problems.

**Closed by mafrahm** 2024-08-16 09:01 UTC
